console.log("hello");
console.log("good morning");
console.log("this is js");
console.log("web development");
console.log("laptop");
console.log("evening");
console.log("mobile phone");
console.log("network");
console.log("fronthend");
console.log("backend");


console.log(4435);
console.log(78645);
console.log(3467);
console.log(79979);
console.log(35678);
console.log(787);
console.log(383944);
console.log(7297);
console.log(737);
console.log(2983);


console.log(true);
console.log(true);
console.log(true);
console.log(true);
console.log(true);


console.log(false);
console.log(false);
console.log(false);
console.log(false);
console.log(false);